/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package verafoute.view;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import verafoute.entity.ConvertBarangToObject;
import verafoute.entity.barang;
import verafoute.entity.login;
import verafoute.entity.transaksi;

/**
 *
 * @author hp
 */
public class HalamanUser extends javax.swing.JFrame {
    
    /**
     * Creates new form HalamanUser
     */
    public HalamanUser() {
        initComponents();
        setDataBarang();
        setNamaPembeli();
    }

    private void setDataBarang(){
        ConvertBarangToObject cbto = new ConvertBarangToObject();
        String[][] dataBarang = cbto.getBarang();
        tblDisplayBarang.setModel(new javax.swing.table.DefaultTableModel
        (dataBarang,
         new String[]{
             "ID Barang","Nama","Harga","Stok","ID Kategori"
         })
        );
    }
    
    private void setNamaPembeli(){
        login p = new login();
        txtid_p.setText(p.getNama_p());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlTableBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayBarang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        pnlDetailBarang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtnama_b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtjml_t = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_kategori = new javax.swing.JComboBox<>();
        btncek_harga = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtid_b = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtid_p = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotal_t = new javax.swing.JTextField();
        dtptgl_t = new datechooser.beans.DateChooserCombo();
        btnbeli_barang = new javax.swing.JButton();
        pnlOrderDetail = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar1.setRollover(true);

        btnHome.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verafoute/icon/archive.png"))); // NOI18N
        btnHome.setText("verafoute");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        jToolBar1.add(btnHome);

        jLabel1.setText("                                                                                                                                                                                                                                                                                                         ");
        jToolBar1.add(jLabel1);

        btnKeluar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verafoute/icon/sign-out (1).png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setFocusable(false);
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKeluar);

        pnlUtama.setBackground(new java.awt.Color(102, 204, 255));
        pnlUtama.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(102, 204, 255));

        pnlTableBarang.setBackground(new java.awt.Color(102, 204, 255));

        tblDisplayBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDisplayBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplayBarang);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setText("List Barang");

        javax.swing.GroupLayout pnlTableBarangLayout = new javax.swing.GroupLayout(pnlTableBarang);
        pnlTableBarang.setLayout(pnlTableBarangLayout);
        pnlTableBarangLayout.setHorizontalGroup(
            pnlTableBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlTableBarangLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTableBarangLayout.setVerticalGroup(
            pnlTableBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pnlDetailBarang.setBackground(new java.awt.Color(102, 204, 255));
        pnlDetailBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Nama Barang :");
        pnlDetailBarang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        txtnama_b.setEditable(false);
        pnlDetailBarang.add(txtnama_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 180, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Jumlah Barang :");
        pnlDetailBarang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        txtjml_t.setEnabled(false);
        pnlDetailBarang.add(txtjml_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 180, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Kategori Barang :");
        pnlDetailBarang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Kategori Barang--", "1 -- Alat Kebersihan", "2 -- Alat Masak", "3 -- Tempat Penyimpanan", "4 -- Alat Mandi", "5 -- Lain-lain" }));
        cb_kategori.setEnabled(false);
        pnlDetailBarang.add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 180, -1));

        btncek_harga.setText("Cek Harga");
        btncek_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncek_hargaActionPerformed(evt);
            }
        });
        pnlDetailBarang.add(btncek_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("ID Barang :");
        pnlDetailBarang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        txtid_b.setEditable(false);
        txtid_b.setText("--ID Barang--");
        pnlDetailBarang.add(txtid_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 180, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel7.setText("Detail Pembelian");
        pnlDetailBarang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Tanggal Beli : ");
        pnlDetailBarang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Nama Pembeli : ");
        pnlDetailBarang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        txtid_p.setEditable(false);
        pnlDetailBarang.add(txtid_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 180, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("Total Harga :");
        pnlDetailBarang.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        txttotal_t.setEditable(false);
        pnlDetailBarang.add(txttotal_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 180, -1));

        dtptgl_t.setEnabled(false);
        dtptgl_t.setLocked(true);
        pnlDetailBarang.add(dtptgl_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 180, -1));

        btnbeli_barang.setText("Beli Barang");
        btnbeli_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeli_barangActionPerformed(evt);
            }
        });
        pnlDetailBarang.add(btnbeli_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTableBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDetailBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDetailBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(pnlTableBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlUtama.add(pnlHome, "cardHome");

        pnlOrderDetail.setBackground(new java.awt.Color(102, 204, 255));
        pnlOrderDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel11.setText("Perhatian!");
        pnlOrderDetail.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel12.setText("Hubungi nomor berikut +62 813 - 8678 - 1414");
        pnlOrderDetail.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel13.setText("Pesanan anda sedang dalam perjalanan");
        pnlOrderDetail.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel14.setText("Apabila dalam 1 x 24 jam pesanan anda belum sampai");
        pnlOrderDetail.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        pnlUtama.add(pnlOrderDetail, "cardOrderDetail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardHome");
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        new HalamanLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btncek_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncek_hargaActionPerformed
        int row = tblDisplayBarang.getSelectedRow();
        String harga_b = tblDisplayBarang.getValueAt(row, 2).toString();
        int total = Integer.parseInt(harga_b)*Integer.parseInt(txtjml_t.getText());
        txttotal_t.setText(Integer.toString(total));
    }//GEN-LAST:event_btncek_hargaActionPerformed

    private void tblDisplayBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayBarangMouseClicked
        int row = tblDisplayBarang.getSelectedRow();
        String id_b = tblDisplayBarang.getValueAt(row, 0).toString();
        String nama_b = tblDisplayBarang.getValueAt(row, 1).toString();
        String id_k = tblDisplayBarang.getValueAt(row, 4).toString();
        
        dtptgl_t.setText("");
        txtid_b.setText("");
        txtjml_t.setText("");
        txttotal_t.setText("");
        
        txtid_b.setText(id_b);
        txtnama_b.setText(nama_b);
        cb_kategori.setSelectedIndex(Integer.parseInt(id_k));
        
        txtjml_t.setEnabled(true);
    }//GEN-LAST:event_tblDisplayBarangMouseClicked

    private void btnbeli_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeli_barangActionPerformed
        login p = new login();
        String tgl_t = dtptgl_t.getText();
        int id_b = Integer.parseInt(txtid_b.getText());
        int jml_t = Integer.parseInt(txtjml_t.getText());
        int total_t = Integer.parseInt(txttotal_t.getText());
        int id_p = p.getId_p();
        int row = tblDisplayBarang.getSelectedRow();
        String stok_b = tblDisplayBarang.getValueAt(row, 3).toString();
        int stok = Integer.parseInt(stok_b)-jml_t;
        if(stok<0){
            JOptionPane.showMessageDialog(null, "Jumlah barang melebihi stok yang tersedia!");
        }
        else {
            int cek = JOptionPane.showConfirmDialog(this, "Anda yakin ingin membeli barang yang dipilih?", "Peringatan!", JOptionPane.YES_NO_OPTION);
            if (cek == JOptionPane.YES_OPTION) {
                barang b = new barang(id_b, stok);
                verafoute.controller.barangController bc = new verafoute.controller.barangController();
                int hasil = bc.updateS(b);
                if(hasil>0){
                    transaksi t = new transaksi(tgl_t, id_b, jml_t, total_t, id_p);
                    verafoute.controller.transaksiController tc = new verafoute.controller.transaksiController();
                    hasil = tc.insertT(t);
                    if(hasil >0){
                        JOptionPane.showMessageDialog(null, "Berhasil Memesan!");

                        cl = (CardLayout) pnlUtama.getLayout();
                        cl.show(pnlUtama, "cardOrderDetail");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Transaksi gagal, coba lagi!");
                    }
                    dtptgl_t.setText("");
                    txtid_b.setText("");
                    txtjml_t.setText("");
                    txttotal_t.setText("");
                    setDataBarang();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Stok gagal diubah");
                }
            }
            
        }
        
    }//GEN-LAST:event_btnbeli_barangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUser().setVisible(true);
            }
        });
    }

    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnbeli_barang;
    private javax.swing.JButton btncek_harga;
    private javax.swing.JComboBox<String> cb_kategori;
    private datechooser.beans.DateChooserCombo dtptgl_t;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlDetailBarang;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlOrderDetail;
    private javax.swing.JPanel pnlTableBarang;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tblDisplayBarang;
    private javax.swing.JTextField txtid_b;
    private javax.swing.JTextField txtid_p;
    private javax.swing.JTextField txtjml_t;
    private javax.swing.JTextField txtnama_b;
    private javax.swing.JTextField txttotal_t;
    // End of variables declaration//GEN-END:variables
}
