/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package verafoute.view;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import verafoute.entity.ConvertBarangToObject;
import verafoute.entity.ConvertPembeliToObject;
import verafoute.entity.ConvertTransaksiToObject;
import verafoute.entity.barang;
import verafoute.entity.pembeli;

/**
 *
 * @author hp
 */
public class HalamanAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HalamanAdmin
     */
    public HalamanAdmin() {
        initComponents();
        setDataBarang();
        setDataPembeli();
        setDataTransaksi();
    }
    
    private void setDataBarang(){
        ConvertBarangToObject cbto = new ConvertBarangToObject();
        String[][] dataBarang = cbto.getBarang();
        tbBarang.setModel(new javax.swing.table.DefaultTableModel
        (dataBarang,
         new String[]{
             "ID Barang","Nama","Harga","Stok","ID Kategori", "Nama Kategori"
         })
        );
    }
    
    private void setDataPembeli(){
        ConvertPembeliToObject cpto = new ConvertPembeliToObject();
        String[][] dataPembeli = cpto.getPembeli();
        tbPembeli.setModel(new javax.swing.table.DefaultTableModel
        (dataPembeli,
         new String[]{
             "ID Pembeli","Nama","Alamat","No Telepon","Username","Password"
         })
        );
    }
    
    private void setDataTransaksi(){
        ConvertTransaksiToObject ctto = new ConvertTransaksiToObject();
        String[][] dataTransaksi = ctto.getTransaksi();
        tbTransaksi.setModel(new javax.swing.table.DefaultTableModel
        (dataTransaksi,
         new String[]{
             "ID Transaksi","Tanggal Transaksi","Nama Barang","Jumlah","Total Harga","Nama Pembeli"
         })
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnBarang = new javax.swing.JButton();
        btnPembeli = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        pnlAdmin = new javax.swing.JPanel();
        lblHalamanAdmin = new javax.swing.JLabel();
        pnlBarang = new javax.swing.JPanel();
        pnlInputBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtid_b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnama_b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtharga_b = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtstok_b = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_kategori = new javax.swing.JComboBox<>();
        btnInsertBarang = new javax.swing.JButton();
        btnUpdateBarang = new javax.swing.JButton();
        btnDeleteBarang = new javax.swing.JButton();
        pnlTabelBarang = new javax.swing.JPanel();
        pBarang = new javax.swing.JScrollPane();
        tbBarang = new javax.swing.JTable();
        pnlPembeli = new javax.swing.JPanel();
        pnlInputPembeli = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtid_p = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnama_p = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtalamat_p = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtnotelp_p = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtusr_p = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpass_p = new javax.swing.JTextField();
        btnInsertPembeli = new javax.swing.JButton();
        btnUpdatePembeli = new javax.swing.JButton();
        btnDeletePembeli = new javax.swing.JButton();
        pnlTabelPembeli = new javax.swing.JPanel();
        pPembeli = new javax.swing.JScrollPane();
        tbPembeli = new javax.swing.JTable();
        pnlTransaksi = new javax.swing.JPanel();
        pnlTabelTransaksi = new javax.swing.JPanel();
        pTransaksi = new javax.swing.JScrollPane();
        tbTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar1.setRollover(true);

        btnBarang.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verafoute/icon/shopping-bag.png"))); // NOI18N
        btnBarang.setText("Data Barang");
        btnBarang.setFocusable(false);
        btnBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBarang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBarangMouseClicked(evt);
            }
        });
        jToolBar1.add(btnBarang);

        btnPembeli.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnPembeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verafoute/icon/user.png"))); // NOI18N
        btnPembeli.setText("Data Pembeli");
        btnPembeli.setFocusable(false);
        btnPembeli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPembeli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPembeliMouseClicked(evt);
            }
        });
        jToolBar1.add(btnPembeli);

        btnTransaksi.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verafoute/icon/shopping-cart.png"))); // NOI18N
        btnTransaksi.setText("Data Transaksi");
        btnTransaksi.setFocusable(false);
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
        });
        jToolBar1.add(btnTransaksi);

        jLabel1.setText("                                                                                                                                                                                                           ");
        jToolBar1.add(jLabel1);

        btnKeluar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verafoute/icon/sign-out (1).png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setFocusable(false);
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKeluar);

        pnlAdmin.setBackground(new java.awt.Color(102, 204, 255));
        pnlAdmin.setLayout(new java.awt.CardLayout());

        lblHalamanAdmin.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblHalamanAdmin.setText("Halaman Admin");
        pnlAdmin.add(lblHalamanAdmin, "card4");

        pnlInputBarang.setBackground(new java.awt.Color(102, 204, 255));
        pnlInputBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("ID Barang :");
        pnlInputBarang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtid_b.setText("--Auto Increment--");
        txtid_b.setEnabled(false);
        pnlInputBarang.add(txtid_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 180, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Nama Barang :");
        pnlInputBarang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        pnlInputBarang.add(txtnama_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 180, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Harga Barang :");
        pnlInputBarang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        pnlInputBarang.add(txtharga_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 180, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Stok Barang :");
        pnlInputBarang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        pnlInputBarang.add(txtstok_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 180, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Kategori Barang :");
        pnlInputBarang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Kategori Barang--", "1 -- Alat Kebersihan", "2 -- Alat Masak", "3 -- Tempat Penyimpanan", "4 -- Alat Mandi", "5 -- Lain-lain" }));
        pnlInputBarang.add(cb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, -1));

        btnInsertBarang.setText("Insert");
        btnInsertBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertBarangActionPerformed(evt);
            }
        });
        pnlInputBarang.add(btnInsertBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        btnUpdateBarang.setText("Update");
        btnUpdateBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBarangActionPerformed(evt);
            }
        });
        pnlInputBarang.add(btnUpdateBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        btnDeleteBarang.setText("Delete");
        btnDeleteBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBarangActionPerformed(evt);
            }
        });
        pnlInputBarang.add(btnDeleteBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        pnlTabelBarang.setBackground(new java.awt.Color(102, 204, 255));

        tbBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBarangMouseClicked(evt);
            }
        });
        pBarang.setViewportView(tbBarang);

        javax.swing.GroupLayout pnlTabelBarangLayout = new javax.swing.GroupLayout(pnlTabelBarang);
        pnlTabelBarang.setLayout(pnlTabelBarangLayout);
        pnlTabelBarangLayout.setHorizontalGroup(
            pnlTabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelBarangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTabelBarangLayout.setVerticalGroup(
            pnlTabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBarangLayout = new javax.swing.GroupLayout(pnlBarang);
        pnlBarang.setLayout(pnlBarangLayout);
        pnlBarangLayout.setHorizontalGroup(
            pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTabelBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBarangLayout.setVerticalGroup(
            pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTabelBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBarangLayout.createSequentialGroup()
                        .addComponent(pnlInputBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pnlAdmin.add(pnlBarang, "cardBarang");

        pnlInputPembeli.setBackground(new java.awt.Color(102, 204, 255));
        pnlInputPembeli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("ID Pembeli :");
        pnlInputPembeli.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtid_p.setText("--Auto Increment--");
        txtid_p.setEnabled(false);
        pnlInputPembeli.add(txtid_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 180, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Nama :");
        pnlInputPembeli.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        pnlInputPembeli.add(txtnama_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 180, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("Alamat :");
        pnlInputPembeli.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        pnlInputPembeli.add(txtalamat_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 180, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel19.setText("No Telepon :");
        pnlInputPembeli.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        pnlInputPembeli.add(txtnotelp_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 180, -1));

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setText("Username :");
        pnlInputPembeli.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        pnlInputPembeli.add(txtusr_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setText("Password :");
        pnlInputPembeli.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        pnlInputPembeli.add(txtpass_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 180, -1));

        btnInsertPembeli.setText("Insert");
        btnInsertPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPembeliActionPerformed(evt);
            }
        });
        pnlInputPembeli.add(btnInsertPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        btnUpdatePembeli.setText("Update");
        btnUpdatePembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePembeliActionPerformed(evt);
            }
        });
        pnlInputPembeli.add(btnUpdatePembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        btnDeletePembeli.setText("Delete");
        btnDeletePembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePembeliActionPerformed(evt);
            }
        });
        pnlInputPembeli.add(btnDeletePembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        pnlTabelPembeli.setBackground(new java.awt.Color(102, 204, 255));

        tbPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPembeliMouseClicked(evt);
            }
        });
        pPembeli.setViewportView(tbPembeli);

        javax.swing.GroupLayout pnlTabelPembeliLayout = new javax.swing.GroupLayout(pnlTabelPembeli);
        pnlTabelPembeli.setLayout(pnlTabelPembeliLayout);
        pnlTabelPembeliLayout.setHorizontalGroup(
            pnlTabelPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabelPembeliLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(pPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTabelPembeliLayout.setVerticalGroup(
            pnlTabelPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelPembeliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPembeliLayout = new javax.swing.GroupLayout(pnlPembeli);
        pnlPembeli.setLayout(pnlPembeliLayout);
        pnlPembeliLayout.setHorizontalGroup(
            pnlPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPembeliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTabelPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPembeliLayout.setVerticalGroup(
            pnlPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPembeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTabelPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPembeliLayout.createSequentialGroup()
                        .addComponent(pnlInputPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pnlAdmin.add(pnlPembeli, "cardPembeli");

        pnlTabelTransaksi.setBackground(new java.awt.Color(102, 204, 255));

        tbTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTransaksiMouseClicked(evt);
            }
        });
        pTransaksi.setViewportView(tbTransaksi);

        javax.swing.GroupLayout pnlTabelTransaksiLayout = new javax.swing.GroupLayout(pnlTabelTransaksi);
        pnlTabelTransaksi.setLayout(pnlTabelTransaksiLayout);
        pnlTabelTransaksiLayout.setHorizontalGroup(
            pnlTabelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelTransaksiLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(pTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        pnlTabelTransaksiLayout.setVerticalGroup(
            pnlTabelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlTransaksiLayout = new javax.swing.GroupLayout(pnlTransaksi);
        pnlTransaksi.setLayout(pnlTransaksiLayout);
        pnlTransaksiLayout.setHorizontalGroup(
            pnlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTabelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnlTransaksiLayout.setVerticalGroup(
            pnlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTabelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAdmin.add(pnlTransaksi, "cardTransaksi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertBarangActionPerformed
        String nama_b = txtnama_b.getText();
        int harga_b = Integer.parseInt(txtharga_b.getText());
        int stok_b = Integer.parseInt(txtstok_b.getText());
        int id_k = cb_kategori.getSelectedIndex();
        barang b = new barang(nama_b, harga_b, stok_b, id_k);
        verafoute.controller.barangController bc = new verafoute.controller.barangController();
        int hasil = bc.insertB(b);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan");
            setDataBarang();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal dimasukkan");
        }
        txtnama_b.setText("");
        txtharga_b.setText("");
        txtstok_b.setText("");
        cb_kategori.setSelectedIndex(0);
    }//GEN-LAST:event_btnInsertBarangActionPerformed

    private void btnUpdateBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBarangActionPerformed
        int id_b = Integer.parseInt(txtid_b.getText());
        String nama_b = txtnama_b.getText();
        int harga_b = Integer.parseInt(txtharga_b.getText());
        int stok_b = Integer.parseInt(txtstok_b.getText());
        int id_k = cb_kategori.getSelectedIndex();
        barang b = new barang(id_b, nama_b, harga_b, stok_b, id_k);
        verafoute.controller.barangController bc = new verafoute.controller.barangController();
        int hasil = bc.updateB(b);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataBarang();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
        txtid_b.setText("--Auto Increment--");
        txtnama_b.setText("");
        txtharga_b.setText("");
        txtstok_b.setText("");
        cb_kategori.setSelectedIndex(0);
    }//GEN-LAST:event_btnUpdateBarangActionPerformed

    private void btnDeleteBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBarangActionPerformed
        int id_b = Integer.parseInt(txtid_b.getText());
        verafoute.controller.barangController bc = new verafoute.controller.barangController();
        int hasil = bc.DeleteB(id_b);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            setDataBarang();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
        txtid_b.setText("--Auto Increment--");
        txtnama_b.setText("");
        txtharga_b.setText("");
        txtstok_b.setText("");
        cb_kategori.setSelectedIndex(0);
    }//GEN-LAST:event_btnDeleteBarangActionPerformed

    private void tbBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBarangMouseClicked
        int row = tbBarang.getSelectedRow();
        String id_b = tbBarang.getValueAt(row, 0).toString();
        String nama_b = tbBarang.getValueAt(row, 1).toString();
        String harga_b = tbBarang.getValueAt(row, 2).toString();
        String stok_b = tbBarang.getValueAt(row, 3).toString();
        String id_k = tbBarang.getValueAt(row, 4).toString();
        txtid_b.setText(id_b);
        txtnama_b.setText(nama_b);
        txtharga_b.setText(harga_b);
        txtstok_b.setText(stok_b);
        cb_kategori.setSelectedIndex(Integer.parseInt(id_k));
    }//GEN-LAST:event_tbBarangMouseClicked

    private void btnBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseClicked
        cl = (CardLayout) pnlAdmin.getLayout();
        cl.show(pnlAdmin, "cardBarang");
    }//GEN-LAST:event_btnBarangMouseClicked

    private void btnInsertPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPembeliActionPerformed
        String nama_p = txtnama_p.getText();
        String alamat_p = txtalamat_p.getText();
        String notelp_p = txtnotelp_p.getText();
        String username_p = txtusr_p.getText();
        String password_p = txtpass_p.getText();
        pembeli p = new pembeli(nama_p, alamat_p, notelp_p, username_p, password_p);
        verafoute.controller.pembeliController pc = new verafoute.controller.pembeliController();
        int hasil = pc.insertP(p);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan");
            setDataPembeli();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal dimasukkan");
        }
        txtid_p.setText("--Auto Increment--");
        txtnama_p.setText("");
        txtalamat_p.setText("");
        txtnotelp_p.setText("");
        txtusr_p.setText("");
        txtpass_p.setText("");

    }//GEN-LAST:event_btnInsertPembeliActionPerformed

    private void btnUpdatePembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePembeliActionPerformed
        int id_p = Integer.parseInt(txtid_p.getText());
        String nama_p = txtnama_p.getText();
        String alamat_p = txtalamat_p.getText();
        String notelp_p = txtnotelp_p.getText();
        String username_p = txtusr_p.getText();
        String password_p = txtpass_p.getText();
        pembeli p = new pembeli(id_p, nama_p, alamat_p, notelp_p, username_p, password_p);
        verafoute.controller.pembeliController pc = new verafoute.controller.pembeliController();
        int hasil = pc.updateP(p);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataPembeli();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
        txtid_p.setText("--Auto Increment--");
        txtnama_p.setText("");
        txtalamat_p.setText("");
        txtnotelp_p.setText("");
        txtusr_p.setText("");
        txtpass_p.setText("");
    }//GEN-LAST:event_btnUpdatePembeliActionPerformed

    private void btnDeletePembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePembeliActionPerformed
        int id_p = Integer.parseInt(txtid_p.getText());
        verafoute.controller.pembeliController pc = new verafoute.controller.pembeliController();
        int hasil = pc.DeleteP(id_p);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            setDataPembeli();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
        txtid_p.setText("--Auto Increment--");
        txtnama_p.setText("");
        txtalamat_p.setText("");
        txtnotelp_p.setText("");
        txtusr_p.setText("");
        txtpass_p.setText("");
    }//GEN-LAST:event_btnDeletePembeliActionPerformed

    private void tbPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPembeliMouseClicked
        int row = tbPembeli.getSelectedRow();
        String id_p = tbPembeli.getValueAt(row, 0).toString();
        String nama_p = tbPembeli.getValueAt(row, 1).toString();
        String alamat_p = tbPembeli.getValueAt(row, 2).toString();
        String notelp_p = tbPembeli.getValueAt(row, 3).toString();
        String username_p = tbPembeli.getValueAt(row, 4).toString();
        String password_p = tbPembeli.getValueAt(row, 5).toString();
        txtid_p.setText(id_p);
        txtnama_p.setText(nama_p);
        txtalamat_p.setText(alamat_p);
        txtnotelp_p.setText(notelp_p);
        txtusr_p.setText(username_p);
        txtpass_p.setText(password_p);
    }//GEN-LAST:event_tbPembeliMouseClicked

    private void btnPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPembeliMouseClicked
        cl = (CardLayout) pnlAdmin.getLayout();
        cl.show(pnlAdmin, "cardPembeli");
    }//GEN-LAST:event_btnPembeliMouseClicked

    private void tbTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTransaksiMouseClicked
        //
    }//GEN-LAST:event_tbTransaksiMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        cl = (CardLayout) pnlAdmin.getLayout();
        cl.show(pnlAdmin, "cardTransaksi");
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        new HalamanLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanAdmin().setVisible(true);
            }
        });
    }

    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnDeleteBarang;
    private javax.swing.JButton btnDeletePembeli;
    private javax.swing.JButton btnInsertBarang;
    private javax.swing.JButton btnInsertPembeli;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPembeli;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUpdateBarang;
    private javax.swing.JButton btnUpdatePembeli;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblHalamanAdmin;
    private javax.swing.JScrollPane pBarang;
    private javax.swing.JScrollPane pPembeli;
    private javax.swing.JScrollPane pTransaksi;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlBarang;
    private javax.swing.JPanel pnlInputBarang;
    private javax.swing.JPanel pnlInputPembeli;
    private javax.swing.JPanel pnlPembeli;
    private javax.swing.JPanel pnlTabelBarang;
    private javax.swing.JPanel pnlTabelPembeli;
    private javax.swing.JPanel pnlTabelTransaksi;
    private javax.swing.JPanel pnlTransaksi;
    private javax.swing.JTable tbBarang;
    private javax.swing.JTable tbPembeli;
    private javax.swing.JTable tbTransaksi;
    private javax.swing.JTextField txtalamat_p;
    private javax.swing.JTextField txtharga_b;
    private javax.swing.JTextField txtid_b;
    private javax.swing.JTextField txtid_p;
    private javax.swing.JTextField txtnama_b;
    private javax.swing.JTextField txtnama_p;
    private javax.swing.JTextField txtnotelp_p;
    private javax.swing.JTextField txtpass_p;
    private javax.swing.JTextField txtstok_b;
    private javax.swing.JTextField txtusr_p;
    // End of variables declaration//GEN-END:variables
}
